version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "lib-ruby-parser/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "examples/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "tests/"
    schedule:
      interval: "daily"
