ignore = [
  "src/parser.rs",
  "src/containers/size.rs",
  "src/error/message/external/constructors.rs",
  "src/error/message/external/getters.rs",
  "src/error/message/external/impl_clone.rs",
  "src/error/message/external/impl_debug.rs",
  "src/error/message/external/impl_drop.rs",
  "src/error/message/external/impl_partial_eq.rs",
  "src/error/message/external/predicates.rs",
  "src/error/message/external/variants.rs",
  "src/error/message/native/constructors.rs",
  "src/error/message/native/enum_.rs",
  "src/error/message/native/getters.rs",
  "src/error/message/native/predicates.rs",
  "src/error/message/native/variants.rs",
  "src/error/message/tests.rs",
  "src/nodes/node_enum/external.rs",
  "src/nodes/node_enum/native.rs",
  "src/nodes/types",
  "src/parser.rs",
  "src/reserved_words/list.rs",
  "src/traverse/visitor/visit_gen.rs",
  "tests/loc_matcher/loc_name_gen.rs",
]
