[package]
authors = ["Ilya Bylich <ibylich@gmail.com>"]
description = "Ruby parser"
edition = "2018"
include = ["src/**/*.rs", "Cargo.toml"]
license = "MIT"
name = "lib-ruby-parser"
repository = "https://github.com/lib-ruby-parser/lib-ruby-parser"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
onig = "6"
regex = "1.3.9"

[build-dependencies]
rust-bison-skeleton = "0.6.0"
serde = {version = "1.0", features = ["derive"]}
serde_yaml = {version = "0.8.13"}

[dev-dependencies]
clap = "3.0.0-beta.2"
glob = "0.3.0"
pprof = {version = "0.3", features = ["flamegraph"]}
