[package]
authors = ["Ilya Bylich <ibylich@gmail.com>"]
description = "Ruby parser"
edition = "2018"
include = ["src/**/*.rs", "Cargo.toml"]
license = "MIT"
name = "lib-ruby-parser"
repository = "https://github.com/lib-ruby-parser/lib-ruby-parser"
version = "0.4.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
onig = {version = "6", optional = true}

[build-dependencies]
lib-ruby-parser-nodes = "0.1.0"
rust-bison-skeleton = "0.7.0"

[dev-dependencies]
clap = "3.0.0-beta.2"
glob = "0.3.0"
pprof = {version = "0.3", features = ["flamegraph"]}
