[package]
name = "ruby_parser"
version = "0.1.0"
authors = ["Ilya Bylich <ibylich@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding = "0.2"
regex = "1.3.9"
lazy_static = "1.4.0"
onig = "6"

[[example]]
name = "tokenize"

[[example]]
name = "parse"

[build-dependencies]
rust-bison-skeleton = { path = "../rust-bison-skeleton/rust-bison-skeleton/" }

[dev-dependencies]
clap = "3.0.0-beta.2"
