[package]
authors = ["Ilya Bylich <ibylich@gmail.com>"]
description = "Ruby parser"
edition = "2018"
include = ["src/**/*.rs", "Cargo.toml"]
license = "MIT"
name = "lib-ruby-parser"
repository = "https://github.com/lib-ruby-parser/lib-ruby-parser"
version = "3.0.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

# Uses external structures
compile-with-external-structures = []

# Link with C library that provides external structures
link-external-c-structures = []

# Link with C library that provides external structures
link-external-cpp-structures = []

# Forces building parser.y and all node files
rebuild-grammar = ["lib-ruby-parser-nodes", "rust-bison-skeleton"]

[dependencies]
onig = {version = "6", optional = true}

[build-dependencies]
lib-ruby-parser-nodes = {version = "0.13.0", optional = true}
rust-bison-skeleton = {version = "0.22.0", optional = true}

[profile.dev]
debug-assertions = false

[profile.release]
lto = true

[profile.test]
debug-assertions = true
