[package]
authors = ["Ilya Bylich <ibylich@gmail.com>"]
description = "Ruby parser"
edition = "2021"
include = ["/codegen/**/*.rs", "/src/**/*.rs", "/build.rs", "/Cargo.toml", "/README.md"]
license = "MIT"
name = "lib-ruby-parser"
repository = "https://github.com/lib-ruby-parser/lib-ruby-parser"
version = "4.0.2+ruby-3.1.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

# Codegen parse.y
codegen-y = ["rust-bison-skeleton"]

# Codegen Rust files
codegen-rust = ["lib-ruby-parser-nodes"]

# Enables optional dependencies to run examples
run-examples = ["clap", "glob", "jemallocator", "pprof"]

# Feature specifically for prepare_token_ids example
prepare-token-ids-example = ["cbindgen"]

# Feature specifically for codegen example
codegen-example = ["lib-ruby-parser-nodes", "serde"]

# Enables debug output in all structs
debug-all = ["debug-buffer", "debug-lexer", "debug-parser"]

# Enables debug output from the `Buffer`
debug-buffer = []

# Enables debug output from the `Lexer`
debug-lexer = []

# Enables debug output from the `Parser`
debug-parser = []

# Enables codegen_token_ids example that is used to generate tokens_ids.h for bindings
codegen-token-ids = []

[dependencies]
alloc-from-pool = {version = "1.0.3"}
onig = {version = "6", optional = true}

# Dependencies of examples
cbindgen = {version = "0.20.0", optional = true}
clap = {version = "3.0.5", optional = true, features = ["derive"]}
glob = {version = "0.3.0", optional = true}
jemallocator = {version = "0.3.2", optional = true}
lib-ruby-parser-nodes = {version = "0.52.0", optional = true}
serde = {version = "1.0", features = ["derive"], optional = true}

pprof = {version = "0.8.0", features = ["flamegraph"], optional = true}

[build-dependencies]
lib-ruby-parser-nodes = {version = "0.52.0", optional = true}
rust-bison-skeleton = {version = "0.40.0", optional = true}

[profile.dev]
debug-assertions = false

[profile.release]
lto = true

[profile.test]
debug-assertions = true
