[package]
name = "ruby_parser"
version = "0.1.0"
authors = ["Ilya Bylich <ibylich@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding = "0.2"
regex = "1.3.9"
lazy_static = "1.4.0"
lalrpop-util = "0.19.0"

[[example]]
name = "tokenize"
