name: coverage

# on:
#   push:
#     branches: [ master ]

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.2"

      - name: install bison
        run: |
          brew install bison
          echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
          bison --version

      - name: install ragel
        run: |
          sudo apt-get update
          sudo apt-get install ragel

      - name: codegen
        run: cargo build --package lib-ruby-parser

      - name: cargo-tarpaulin
        run: |
          cargo install cargo-tarpaulin
          make test-cov

      - name: upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
