name: test-c

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: ${{ matrix.build.link-feature }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rustflags:
          - "-Zsanitizer=address"
        build:
          - link-feature: link-external-c-structures
            compile-external-containers: make print-sizes-c libstructures-c.a
            LIB_RUBY_PARSER_PTR_SIZE: 8
            LIB_RUBY_PARSER_MAYBE_PTR_SIZE: 8
            LIB_RUBY_PARSER_LIST_SIZE: 24
            LIB_RUBY_PARSER_STRING_PTR_SIZE: 16
            LIB_RUBY_PARSER_SHARED_BYTE_LIST_SIZE: 16

          - link-feature: link-external-cpp-structures
            compile-external-containers: make print-sizes-cpp libstructures-cpp.a
            LIB_RUBY_PARSER_PTR_SIZE: 8
            LIB_RUBY_PARSER_MAYBE_PTR_SIZE: 8
            LIB_RUBY_PARSER_LIST_SIZE: 24
            LIB_RUBY_PARSER_STRING_PTR_SIZE: 8
            LIB_RUBY_PARSER_SHARED_BYTE_LIST_SIZE: 16

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: compile external containers
        run: cd external && ${{ matrix.build.compile-external-containers }}

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: install bison
        run: |
          brew update
          brew install bison
          echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH

      - name: show bison version
        run: bison --version

      - name: codegen
        run: cargo build --features rebuild-grammar

      - name: run tests
        env:
          RUSTFLAGS: ${{ matrix.rustflags }}
          ASAN_OPTIONS: detect_leaks=1
          CARGO_FEATURES: "compile-with-external-structures,${{ matrix.build.link-feature }},nightly-features"
        run: |
          cargo test --features $CARGO_FEATURES --lib -- --nocapture

          cargo test --features $CARGO_FEATURES --test parser_test -- --nocapture
          cargo test --features $CARGO_FEATURES --test lexer_test -- --nocapture
