name: test-external

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: ${{ matrix.build.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: Compile with external C structures
            build-feature: link-with-external-c-structures
            codegen-feature: codegen-c
            external-implementation-dir: external/c

          - name: Compile with external CXX structures
            build-feature: link-with-external-cpp-structures
            codegen-feature: codegen-cpp
            external-implementation-dir: external/cpp

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: install bison
        run: |
          brew update
          brew install bison
          echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH

      - name: show bison version
        run: bison --version

      - name: codegen
        run: cargo build --features "codegen-y,codegen-rust,${{ matrix.build.codegen-feature }}"

      - name: compile external containers
        env:
          CC: clang
          CXX: clang++
          AR: ar
        run: |
          cd ${{ matrix.build.external-implementation-dir }} && make all
          cat sizes-out

      - name: run tests
        env:
          RUSTFLAGS: "-Zsanitizer=address"
          ASAN_OPTIONS: "detect_leaks=1"
          CARGO_FEATURES: "compile-with-external-structures,${{ matrix.build.build-feature }}"
          LIB_RUBY_PARSER_SIZES_FILEPATH: "${{ matrix.build.external-implementation-dir }}/sizes-out"
        run: |
          cargo test --features $CARGO_FEATURES --lib -- --nocapture

          cargo test --features $CARGO_FEATURES --test lexer_test -- --nocapture
          cargo test --features $CARGO_FEATURES --test parser_test -- --nocapture
